const instruments = [
{"id":"NEU-0001","name":"Adson - Hook","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"56","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0002","name":"Periosteal Elevator - Sharp","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"52","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0003","name":"Periosteal Elevator - Blunt","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"62","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0004","name":"Posterior Fossa Retractor","specialty":"Neuro-Surgical Equipment","shelf":"7 Rear","location":"76","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0005","name":"Sucker - Single","specialty":"Neuro-Surgical Equipment","shelf":"2","location":"10","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0006","name":"Sucker - Set","specialty":"Neuro-Surgical Equipment","shelf":"2","location":"12","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0007","name":"Toothed Forceps","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"58","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0008","name":"Aneurysm Clips - Slimline","specialty":"Neuro-Surgical Equipment","shelf":"8","location":"None","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0009","name":"Aneurysm Clips - Sugita","specialty":"Neuro-Surgical Equipment","shelf":"8","location":"None","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0010","name":"Aneurysm Clips - Sundt AVM","specialty":"Neuro-Surgical Equipment","shelf":"8","location":"None","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0011","name":"Aneurysm Clips - Yasargil","specialty":"Neuro-Surgical Equipment","shelf":"8","location":"None","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0012","name":"Aneurysm Clip Registers","specialty":"Neuro-Surgical Equipment","shelf":"8","location":"None","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0013","name":"Applicator, Raney Clip","specialty":"Neuro-Surgical Equipment","shelf":"6","location":"50","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0014","name":"AVM Clips - Sundt","specialty":"Neuro-Surgical Equipment","shelf":"8","location":"None","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0015","name":"Bactiseal EVDs and VP Shunt Catheters","specialty":"Neuro-Surgical Equipment","shelf":"East Prep","location":"Fridge 3","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0016","name":"Bayonet Forceps - Toothed","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"58","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0017","name":"Bayonet Forceps - Non-Toothed","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"59","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0018","name":"Bipolar Forceps - Disposable Bayonet 1.0mm Tip","specialty":"Neuro-Surgical Equipment","shelf":"3","location":"23","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0019","name":"Bipolar Forceps - Isocool Handles","specialty":"Neuro-Surgical Equipment","shelf":"3","location":"20","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0020","name":"Bipolar Forceps - Isocool Tips 0.5mm and 1.0mm","specialty":"Neuro-Surgical Equipment","shelf":"3","location":"18 + 19","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0021","name":"Bipolar Forceps - Reusable","specialty":"Neuro-Surgical Equipment","shelf":"3","location":"21","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0022","name":"Bone Nibbler - Lampert","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"82","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0023","name":"Bone Nibbler - Leksell","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"82","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0024","name":"Bone Nibbler - Northfields","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"82","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0025","name":"Brain Needle / Cushings Brain Cannula","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"54","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0026","name":"Brain Retractors / Malleables","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"57","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0027","name":"Budde Halo Retractor","specialty":"Neuro-Surgical Equipment","shelf":"8","location":"None","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0028","name":"Budde Halo Pattie Tray","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"60","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0029","name":"Cairns Cranial Elevator","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"53","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0030","name":"Castroviejo Needle Holder","specialty":"Neuro-Surgical Equipment","shelf":"8","location":"64","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0031","name":"Cobb Elevator","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"52","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0032","name":"Craniotomy Drape","specialty":"Neuro-Surgical Equipment","shelf":"1","location":"1","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0033","name":"Cushing Brain Cannula","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"54","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0034","name":"Cushing Forceps","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"58","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0035","name":"Dissector - McCormick","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"51","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0036","name":"Dissector - Watson Cheyne","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"52","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0037","name":"Dissector - Swedish","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"52","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0038","name":"Dural Hook","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"55","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0039","name":"Dural Scissors","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"61","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0040","name":"Fish Hook Retractor","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"75","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0041","name":"Gelpi Retractor","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"77","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0042","name":"Gillies Toothed Forceps","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"59","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0043","name":"Hudson Brace","specialty":"Neuro-Surgical Equipment","shelf":"8","location":"70","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0044","name":"Hudson Burr","specialty":"Neuro-Surgical Equipment","shelf":"8","location":"70","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0045","name":"Kerrison Rongeur 1mm","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"80","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0046","name":"Kerrison Rongeur 2mm","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"80","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0047","name":"Kerrison Rongeur 3mm","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"80","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0048","name":"Kerrison Rongeur 4mm","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"80","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0049","name":"Kerrison Rongeur 5mm","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"80","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0050","name":"Laminectomy Retractor","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"73","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0051","name":"De Martel Guide / Wire Guide","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"60","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0052","name":"Dental Mirror","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"60","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0053","name":"Dissector, McCormick","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"52","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0054","name":"Distractor Pin Set - Caspar","specialty":"Neuro-Surgical Equipment","shelf":"6 Rear","location":"None","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0055","name":"Drape, Craniotomy","specialty":"Neuro-Surgical Equipment","shelf":"1","location":"1","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0056","name":"Drills - Midas Rex","specialty":"Neuro-Surgical Equipment","shelf":"3","location":"17","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0057","name":"Midas Rex Burrs","specialty":"Neuro-Surgical Equipment","shelf":"Th12","location":"Burr Trolley","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0058","name":"Midas Rex Attachments","specialty":"Neuro-Surgical Equipment","shelf":"2","location":"9","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0059","name":"Dural Hooks - Sharp","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"56","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0060","name":"Dural Hooks - Blunt","specialty":"Neuro-Surgical Equipment","shelf":"6","location":"48","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0061","name":"Dural Scissor McKissock","specialty":"Neuro-Surgical Equipment","shelf":"2 Rear","location":"None","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0062","name":"Duragen","specialty":"Neuro-Surgical Equipment","shelf":"East Prep","location":"Fridge 3","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0063","name":"Duraseal","specialty":"Neuro-Surgical Equipment","shelf":"East Prep","location":"Fridge 3","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0064","name":"Elastic Bands Non-latex","specialty":"Neuro-Surgical Equipment","shelf":"4","location":"33","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0065","name":"Elevator - Adson","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"52","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0066","name":"Elevator - Cairns","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"53","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0067","name":"Elevator - Cobbs","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"79","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0068","name":"Elevator - Farabeuf","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"53","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0069","name":"EVD Bactiseal Catheters 1.5, 1.9mm","specialty":"Neuro-Surgical Equipment","shelf":"East Prep","location":"Fridge","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0070","name":"EVD Catheters Non-Antibacterial","specialty":"Neuro-Surgical Equipment","shelf":"6","location":"43","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0071","name":"EVD Drainage System EDS 3","specialty":"Neuro-Surgical Equipment","shelf":"6","location":"None","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0072","name":"EVD Transducer Line PX600","specialty":"Neuro-Surgical Equipment","shelf":"6","location":"47","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0073","name":"Farabeuf Elevator","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"53","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0074","name":"Forceps Non-Toothed Bayonet","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"59","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0075","name":"Forceps Non-Toothed Jefferson","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"59","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0076","name":"Forceps Non-Toothed Tumour Holding","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"59","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0077","name":"Forceps Non-Toothed Yasargil","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"59","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0078","name":"Forceps Non-Toothed Micro","specialty":"Neuro-Surgical Equipment","shelf":"8","location":"64","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0079","name":"Forceps Toothed Adson","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"58","area":"Main Neuro Shelves","status":"Available"},
{"id":"NEU-0080","name":"Forceps Toothed Bayonet","specialty":"Neuro-Surgical Equipment","shelf":"7","location":"58","area":"Main Neuro Shelves","status":"Available"}
,
{"id":"GEN-0001","name":"Aarons Cone (Hydatid Funnel)","specialty":"General Surgery","shelf":"K","row":"1","location":"62","area":"General Surgery Shelves","status":"Available"},
{"id":"GEN-0002","name":"Absorba Tack","specialty":"General Surgery","shelf":"O","row":"1","location":"232","area":"General Surgery Shelves","status":"Available"},
{"id":"GEN-0003","name":"Adson Forceps - Toothed","specialty":"General Surgery","shelf":"K","row":"2","location":"99","area":"General Surgery Shelves","status":"Available"},
{"id":"GEN-0004","name":"Adson Forceps - Non Toothed","specialty":"General Surgery","shelf":"K","row":"2","location":"99","area":"General Surgery Shelves","status":"Available"},
{"id":"GEN-0005","name":"Adson Sucker 12F","specialty":"General Surgery","shelf":"K","row":"4","location":"123","area":"General Surgery Shelves","status":"Available"}
]
